#!/bin/bash
cd
if [ -e "/data/data/com.termux/files/home/storage" ]; then
    rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
pkg update -y
. <(curl -fsSL https://raw.githubusercontent.com/zam2109/Toolrejoin/refs/heads/main/termux-change-repo.sh)
pkg upgrade -y
pkg install -y python
pkg install -y python-pip
pip install urllib3 idna
export CFLAGS="-Wno-error=implicit-function-declaration"
curl -Ls "https://raw.githubusercontent.com/zam2109/Auto-Buy-Ugphone-Tool-Setub/refs/heads/main/buyugphone.py" -o /sdcard/Download/buyugphone.py
